CREATE DATABASE `fms_exit_process_annex` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
use fms_exit_process_annex;
CREATE TABLE `exit_requests` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `employee_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `department` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hod` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hod_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `doj` date DEFAULT NULL,
  `reporting_doer` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reporting_doer_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_of_exit` date NOT NULL,
  `status` enum('OPEN','CLOSED','REJECTED','CANCELLED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OPEN',
  `workflow_stage` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'P1',
  `stage_started_at` datetime DEFAULT NULL,
  `deadline_at` datetime DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `p1_remarks` text COLLATE utf8mb4_unicode_ci,
  `p1_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p1_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p1_done_at` datetime DEFAULT NULL,
  `p2_decision` enum('YES','NO') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p2_remarks` text COLLATE utf8mb4_unicode_ci,
  `p2_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p2_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p2_done_at` datetime DEFAULT NULL,
  `p3_remarks` text COLLATE utf8mb4_unicode_ci,
  `p3_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p3_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p3_done_at` datetime DEFAULT NULL,
  `p4_status` enum('PENDING','DONE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `p4_remarks` text COLLATE utf8mb4_unicode_ci,
  `p4_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p4_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p4_done_at` datetime DEFAULT NULL,
  `p5_remarks` text COLLATE utf8mb4_unicode_ci,
  `p5_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p5_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p5_done_at` datetime DEFAULT NULL,
  `p6_remarks` text COLLATE utf8mb4_unicode_ci,
  `p6_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p6_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p6_done_at` datetime DEFAULT NULL,
  `p7_remarks` text COLLATE utf8mb4_unicode_ci,
  `p7_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p7_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p7_done_at` datetime DEFAULT NULL,
  `p8_remarks` text COLLATE utf8mb4_unicode_ci,
  `p8_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p8_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p8_done_at` datetime DEFAULT NULL,
  `p9_status` enum('PENDING','DONE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `p9_new_assigned_person` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p9_deadline` datetime DEFAULT NULL,
  `p9_remarks` text COLLATE utf8mb4_unicode_ci,
  `p9_attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p9_done_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p9_done_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_employee_code` (`employee_code`),
  KEY `idx_status` (`status`),
  KEY `idx_workflow_stage` (`workflow_stage`),
  KEY `idx_date_of_exit` (`date_of_exit`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_hod_id` (`hod_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_p2_decision` (`p2_decision`),
  KEY `idx_p4_status` (`p4_status`),
  KEY `idx_p9_status` (`p9_status`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='HR Exit Process workflow P1-P9 (Annexure 1)';
CREATE TABLE `exit_stage_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `exit_request_id` int unsigned NOT NULL,
  `stage` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `done_by` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `done_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `remarks` text COLLATE utf8mb4_unicode_ci,
  `attachment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_exit_request_id` (`exit_request_id`),
  KEY `idx_stage` (`stage`),
  KEY `idx_done_by` (`done_by`),
  KEY `idx_done_at` (`done_at`),
  CONSTRAINT `fk_log_exit` FOREIGN KEY (`exit_request_id`) REFERENCES `exit_requests` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Audit trail for every action in exit workflow';
CREATE TABLE `pc_updates` (
  `update_id` int NOT NULL AUTO_INCREMENT,
  `task_id` int DEFAULT NULL,
  `task_name` varchar(255) DEFAULT NULL,
  `from_stage` varchar(10) DEFAULT NULL,
  `current_stage` varchar(10) DEFAULT NULL,
  `planned_end_time` datetime DEFAULT NULL,
  `remark` text,
  `next_planned_end_time` datetime DEFAULT NULL,
  `followup_stage` varchar(10) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `emp_id` varchar(255) DEFAULT NULL,
  `actual_emp_code` varchar(255) DEFAULT NULL,
  `actual_emp_name` varchar(255) DEFAULT NULL,
  `hod_emp_code` varchar(255) DEFAULT NULL,
  `1st_planned_end_time` datetime DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `fms_name` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`update_id`),
  KEY `task_id` (`task_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `task_updates` (
  `update_id` int NOT NULL DEFAULT '0',
  `task_id` int DEFAULT NULL,
  `task_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `from_stage` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `to_stage` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `remark` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `attachment_path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `planned_end_time` datetime DEFAULT NULL,
  `decision` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `emp_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `actual_time` datetime DEFAULT NULL,
  `allocate_to` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `allocate_emp_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `project` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fms_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'fms_con_sangamtask'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tasks` (
  `task_id` int NOT NULL DEFAULT '0',
  `task_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `current_stage` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `from_stage` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `remark` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `attachment_path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `planned_end_time` datetime DEFAULT NULL,
  `submit_emp_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `emp_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `emp_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `actual_emp_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `hod_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `hod_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `actual_time` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `allocate_to` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `allocate_emp_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `created_emp_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `project` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `task_details` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `1st_planned_end_time` datetime DEFAULT NULL,
  `pc_update_stage` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fms_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'fms_con_sangamtask',
  UNIQUE KEY `uq_task_name` (`task_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
